import type { PalletPackingStyle } from "./packerTypes";
import type { SelectionMode } from "./packerCoreTypes";

export interface CandidateScoreInputs {
  rectCount: number;
  cornerCount: number;
  taperAllowed: boolean;
  rescue: boolean;
  wallCoverageWeight: number;
  wallsCoverage: number;
  wallsBalance: number;
  wallsSegments: number;
  gapsEmptyRatio: number;
  gapEmptyPenalty: number;
  gapsLargestGapRatio: number;
  largestGapPenalty: number;
  avgSupport: number;
  lowSupportCount: number;
  crossBondCount: number;
  baseLayer: boolean;
  exactAlignedCount: number;
  uniformStackMode: boolean;
  alignmentRatio: number;
  hasMeaningfulCrossBond: boolean;
  stronglyColumnLikeLayer: boolean;
  packingStyle: PalletPackingStyle;
  towerPenalty: number;
  pressureMarginSum: number;
  shapeCompactness: number;
  fillRatio: number;
  boundsAreaRatio: number;
  isPartial: boolean;
  componentCount: number;
  finalBatchFragmentPenalty: number;
  centerOccupancy: number;
  centerAxisCoverage: number;
  centerHasGap: boolean;
  centerGapStreak: number;
  mode: SelectionMode;
  insetsMin: number;
  insetsMax: number;
  hasControlledSetback: boolean;
  maxRecommendedEdgeSetback: number;
  lineComplexity: number;
  footprintVariants: number;
  layerIndex: number;
  nearTail: boolean;
  remainingTotalAfterPlacement: number;
  prevCenterOccupancy: number;
  prevWallCoverage: number;
  sameTypeAsPrev: boolean;
  sameLayoutAsPrev: boolean;
  mirroredLayoutAsPrev: boolean;
  cartonHeight: number;
  density: number;
}
