import {
  cumulativeStackLoadSafe,
  findNextZBase,
  tryCenterShiftLayer,
} from "./packerLayerStability";
import {
  findGapPlacement,
  findGapPlacementExhaustive,
  findLowestHeightGapPlacement,
} from "./packerGapPlacement";
import { tryFindBestCandidate, type TryFindBestCandidateDeps } from "./packerCandidateSearch";
import { hashRects } from "./packerGeometryCore";
import { updateStreakMaps } from "./packerFootprintTracking";
import {
  hasAnyNonNeverUprightCandidates,
  hasAnyPreferredUprightCandidates,
} from "./packerPolicy";
import type { HeuristicRunnerDeps } from "./packerHeuristicCore";
import type { PackPalletSharedDeps } from "./packerPackPalletSharedDeps";

export function createHeuristicRunnerDeps(
  shared: PackPalletSharedDeps,
  candidateSearchDeps: TryFindBestCandidateDeps,
): HeuristicRunnerDeps {
  return {
    hasAnyPreferredUprightCandidates,
    hasAnyNonNeverUprightCandidates,
    tryFindBestCandidate: (
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      patternCache,
      profile,
      zBase,
      blockedRects,
      avoidTypeId,
    ) => tryFindBestCandidate(
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      patternCache,
      profile,
      zBase,
      blockedRects,
      avoidTypeId ?? null,
      null,
      true,
      true,
      candidateSearchDeps,
    ),
    findLowestHeightGapPlacement: (
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      blockedRects,
      zBase,
      currentLayerHeight,
      allowUpright,
      preferredDifferentTypeId,
      usedTypeIds,
      minHeightExclusive,
    ) => findLowestHeightGapPlacement(
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      blockedRects,
      zBase,
      currentLayerHeight,
      allowUpright,
      preferredDifferentTypeId,
      usedTypeIds,
      minHeightExclusive,
      shared.gapPlacementDeps,
    ),
    findGapPlacementExhaustive: (
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      blockedRects,
      zBase,
      currentLayerHeight,
      allowUpright,
      preferredDifferentTypeId,
      usedTypeIds,
      heightCeil,
    ) => findGapPlacementExhaustive(
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      blockedRects,
      zBase,
      currentLayerHeight,
      allowUpright,
      preferredDifferentTypeId,
      usedTypeIds,
      heightCeil,
      shared.gapPlacementDeps,
    ),
    findGapPlacement: (
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      blockedRects,
      zBase,
      currentLayerHeight,
      allowUpright,
      preferredDifferentTypeId,
      usedTypeIds,
      heightCeil,
    ) => findGapPlacement(
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      blockedRects,
      zBase,
      currentLayerHeight,
      allowUpright,
      preferredDifferentTypeId,
      usedTypeIds,
      heightCeil,
      shared.gapPlacementDeps,
    ),
    isRectSetPlacementSafe: shared.rectSetPlacementSafeOnPallet,
    isWrapFriendlyLayerShape: shared.isWrapFriendlyLayerShape,
    cumulativeStackLoadSafe: (cartonsInStack) => cumulativeStackLoadSafe(cartonsInStack, shared.stackLoadDeps),
    noCollision: shared.noCollisionOnPallet,
    tryCenterShiftLayer: (placements, placedCartons, belowPlacements, palletInput) => (
      tryCenterShiftLayer(placements, placedCartons, belowPlacements, palletInput, shared.centerShiftDeps)
    ),
    hashRects,
    mirrorHashes: shared.mirrorHashes,
    wallStats: shared.wallStats,
    centerStats: shared.centerStats,
    updateStreakMaps,
    findNextZBase: (placed, currentZ) => findNextZBase(placed, currentZ, shared.EPS),
  };
}
