import {
  findGapPlacement,
  findGapPlacementOptions,
  findGapPlacementExhaustive,
  findGapPlacementExhaustiveOptions,
  findLowestHeightGapPlacement,
} from "./packerGapPlacement";
import type { HeuristicRunnerDeps } from "./packerHeuristicTypes";
import type { PackPalletSharedDeps } from "./packerPackPalletSharedDeps";

type HeuristicGapPlacementResolvers = Pick<
  HeuristicRunnerDeps,
  | "findLowestHeightGapPlacement"
  | "findGapPlacement"
  | "findGapPlacementOptions"
  | "findGapPlacementExhaustive"
  | "findGapPlacementExhaustiveOptions"
>;

export function createHeuristicGapPlacementResolvers(
  shared: PackPalletSharedDeps,
): HeuristicGapPlacementResolvers {
  return {
    findLowestHeightGapPlacement: (
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      blockedRects,
      zBase,
      currentLayerHeight,
      allowUpright,
      preferredDifferentTypeId,
      usedTypeIds,
      minHeightExclusive,
    ) => findLowestHeightGapPlacement(
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      blockedRects,
      zBase,
      currentLayerHeight,
      allowUpright,
      preferredDifferentTypeId,
      usedTypeIds,
      minHeightExclusive,
      shared.gapPlacementDeps,
    ),
    findGapPlacementOptions: (
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      blockedRects,
      zBase,
      currentLayerHeight,
      allowUpright,
      preferredDifferentTypeId,
      usedTypeIds,
      heightCeil,
      maxOptions,
    ) => findGapPlacementOptions(
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      blockedRects,
      zBase,
      currentLayerHeight,
      allowUpright,
      preferredDifferentTypeId,
      usedTypeIds,
      heightCeil,
      maxOptions ?? 6,
      shared.gapPlacementDeps,
    ),
    findGapPlacementExhaustive: (
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      blockedRects,
      zBase,
      currentLayerHeight,
      allowUpright,
      preferredDifferentTypeId,
      usedTypeIds,
      heightCeil,
    ) => findGapPlacementExhaustive(
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      blockedRects,
      zBase,
      currentLayerHeight,
      allowUpright,
      preferredDifferentTypeId,
      usedTypeIds,
      heightCeil,
      shared.gapPlacementDeps,
    ),
    findGapPlacementExhaustiveOptions: (
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      blockedRects,
      zBase,
      currentLayerHeight,
      allowUpright,
      preferredDifferentTypeId,
      usedTypeIds,
      heightCeil,
      maxOptions,
    ) => findGapPlacementExhaustiveOptions(
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      blockedRects,
      zBase,
      currentLayerHeight,
      allowUpright,
      preferredDifferentTypeId,
      usedTypeIds,
      heightCeil,
      maxOptions ?? 6,
      shared.gapPlacementDeps,
    ),
    findGapPlacement: (
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      blockedRects,
      zBase,
      currentLayerHeight,
      allowUpright,
      preferredDifferentTypeId,
      usedTypeIds,
      heightCeil,
    ) => findGapPlacement(
      palletInput,
      remainingCartons,
      state,
      remainingWeight,
      blockedRects,
      zBase,
      currentLayerHeight,
      allowUpright,
      preferredDifferentTypeId,
      usedTypeIds,
      heightCeil,
      shared.gapPlacementDeps,
    ),
  };
}
