import type { AppTopbarProps } from "./AppTopbar.types";

export type TopbarCorePanelsProps = Pick<
  AppTopbarProps,
  | "t"
  | "language"
  | "setLanguage"
  | "workflowMode"
  | "switchWorkflowMode"
  | "topbarPanels"
  | "sampleSave"
  | "settings"
  | "workflowLabel"
  | "currentWorkflowLabel"
  | "workflowGenerationLabel"
  | "workflowManualLabel"
  | "layoutSamplesLabel"
  | "saveLayoutSampleLabel"
  | "loadLayoutSampleLabel"
  | "sampleFolderLabel"
  | "sampleChooseFolderLabel"
  | "sampleChangeFolderLabel"
  | "sampleFolderNotSelectedLabel"
  | "sampleNameLabel"
  | "sampleNamePlaceholder"
  | "sampleStrategyLabel"
  | "sampleStrategyBothLabel"
  | "sampleSaveActionLabel"
  | "sampleSavingLabel"
  | "sampleLoad"
  | "sampleLoadFileLabel"
  | "sampleReloadFolderLabel"
  | "sampleLoadActionLabel"
  | "sampleLoadingLabel"
  | "languageLabel"
  | "settingsLabel"
  | "settingsSaveLabel"
  | "settingsRestoreDefaultsLabel"
  | "uiZoomAndScaleLabel"
  | "shortcutActivationLabel"
  | "shortcutPressLabel"
  | "uiAccessOpenLabel"
  | "uiAccessCloseLabel"
>;
