import type { UseSidebarPropsArgs } from "./sidebarPropsTypes";

export type SidebarBindingArgs = Pick<
  UseSidebarPropsArgs,
  | "workflowMode"
  | "manualCartons"
  | "result"
  | "generationSeedResult"
  | "labels"
  | "handleCalculate"
  | "handleCalculateMissing"
  | "handleGenerateManualAgain"
  | "handleGenerateManualMore"
  | "workflowBusyKind"
  | "switchWorkflowMode"
  | "sampleDatabasePanelVisible"
  | "sampleDatabaseFolderPath"
  | "sampleDatabaseData"
  | "sampleDatabaseLoading"
  | "sampleDatabaseError"
  | "handleChooseSampleDatabaseFolder"
  | "handleReloadSampleDatabase"
  | "sampleDatabaseStatusSummaryText"
  | "sampleGuidanceEnabled"
  | "setSampleGuidanceEnabled"
  | "sampleGuidanceStrengthPercent"
  | "setSampleGuidanceStrengthPercent"
  | "sampleGuidanceCfgScalePercent"
  | "handleSampleGuidanceCfgScalePercentChange"
  | "sampleGuidanceSteps"
  | "handleSampleGuidanceStepsChange"
  | "sampleGuidanceSeed"
  | "handleSampleGuidanceSeedChange"
  | "sampleGuidanceFilter"
  | "setSampleGuidanceFilter"
  | "sampleTemplateLockEnabled"
  | "setSampleTemplateLockEnabled"
>;

export type SidebarSampleDatabaseBindingArgs = Pick<
  SidebarBindingArgs,
  | "workflowMode"
  | "sampleDatabasePanelVisible"
  | "sampleDatabaseFolderPath"
  | "sampleDatabaseData"
  | "sampleDatabaseLoading"
  | "sampleDatabaseError"
  | "handleChooseSampleDatabaseFolder"
  | "handleReloadSampleDatabase"
  | "sampleDatabaseStatusSummaryText"
  | "sampleGuidanceEnabled"
  | "setSampleGuidanceEnabled"
  | "sampleGuidanceStrengthPercent"
  | "setSampleGuidanceStrengthPercent"
  | "sampleGuidanceCfgScalePercent"
  | "handleSampleGuidanceCfgScalePercentChange"
  | "sampleGuidanceSteps"
  | "handleSampleGuidanceStepsChange"
  | "sampleGuidanceSeed"
  | "handleSampleGuidanceSeedChange"
  | "sampleGuidanceFilter"
  | "setSampleGuidanceFilter"
  | "sampleTemplateLockEnabled"
  | "setSampleTemplateLockEnabled"
  | "labels"
>;
