import type {
  BuildSampleDatabaseSidebarBindingsArgs,
  SampleDatabaseSidebarBindings,
} from "./sidebarPropsSampleDatabaseTypes";

export function buildSampleDatabaseSidebarBindings({
  workflowMode,
  sampleDatabaseFolderPath,
  sampleDatabaseSummary,
  sampleDatabaseLoading,
  sampleDatabaseError,
  handleChooseSampleDatabaseFolder,
  handleReloadSampleDatabase,
  sampleDatabaseStatusSummaryText,
  sampleGuidanceEnabled,
  setSampleGuidanceEnabled,
  sampleGuidanceStrengthPercent,
  setSampleGuidanceStrengthPercent,
  sampleGuidanceCfgScalePercent,
  handleSampleGuidanceCfgScalePercentChange,
  sampleGuidanceSteps,
  handleSampleGuidanceStepsChange,
  sampleGuidanceSeed,
  handleSampleGuidanceSeedChange,
  sampleGuidanceFilter,
  setSampleGuidanceFilter,
  sampleTemplateLockEnabled,
  setSampleTemplateLockEnabled,
  labels,
}: BuildSampleDatabaseSidebarBindingsArgs): SampleDatabaseSidebarBindings {
  return {
    showSampleDatabaseSection: workflowMode === "generation",
    sampleDatabaseFolderPath,
    sampleDatabaseSummary,
    sampleDatabaseLoading,
    sampleDatabaseError,
    onChooseSampleDatabaseFolder: handleChooseSampleDatabaseFolder,
    onReloadSampleDatabase: handleReloadSampleDatabase,
    sampleDatabaseLabel: labels.sampleDatabaseLabel,
    sampleDatabaseFolderLabel: labels.sampleDatabaseFolderLabel,
    sampleDatabaseChooseFolderLabel: labels.sampleDatabaseChooseFolderLabel,
    sampleDatabaseReloadLabel: labels.sampleDatabaseReloadLabel,
    sampleDatabaseScanningLabel: labels.sampleDatabaseScanningLabel,
    sampleDatabaseSummaryPrefix: labels.sampleDatabaseSummaryPrefix,
    sampleDatabaseFolderNotSelectedLabel: labels.sampleFolderNotSelectedLabel,
    sampleDatabaseGuidanceSummary: sampleDatabaseStatusSummaryText,
    sampleGuidanceEnabled,
    onSampleGuidanceEnabledChange: setSampleGuidanceEnabled,
    sampleGuidanceModeLabel: labels.sampleGuidanceSwitchLabel,
    sampleGuidanceModeOnLabel: labels.sampleGuidanceOnLabel,
    sampleGuidanceModeOffLabel: labels.sampleGuidanceOffOptionLabel,
    sampleGuidanceStrengthPercent,
    onSampleGuidanceStrengthPercentChange: setSampleGuidanceStrengthPercent,
    sampleGuidanceStrengthLabel: labels.sampleGuidanceStrengthLabel,
    sampleGuidanceCfgScalePercent,
    onSampleGuidanceCfgScalePercentChange: handleSampleGuidanceCfgScalePercentChange,
    sampleGuidanceCfgScaleLabel: labels.sampleGuidanceCfgScaleLabel,
    sampleGuidanceSteps,
    onSampleGuidanceStepsChange: handleSampleGuidanceStepsChange,
    sampleGuidanceStepsLabel: labels.sampleGuidanceStepsLabel,
    sampleGuidanceSeed,
    onSampleGuidanceSeedChange: handleSampleGuidanceSeedChange,
    sampleGuidanceSeedLabel: labels.sampleGuidanceSeedLabel,
    sampleGuidanceFilter,
    onSampleGuidanceFilterChange: setSampleGuidanceFilter,
    sampleGuidanceFilterLabel: labels.sampleGuidanceFilterLabel,
    sampleGuidanceFilterAllLabel: labels.sampleGuidanceFilterAllLabel,
    sampleGuidanceFilterDimsLabel: labels.sampleGuidanceFilterDimsLabel,
    sampleGuidanceFilterShapeLabel: labels.sampleGuidanceFilterShapeLabel,
    sampleGuidanceFilterExactLabel: labels.sampleGuidanceFilterExactLabel,
    sampleTemplateLockEnabled,
    onSampleTemplateLockEnabledChange: setSampleTemplateLockEnabled,
    sampleTemplateLockLabel: labels.sampleTemplateLockLabel,
    sampleTemplateLockOnLabel: labels.sampleTemplateLockOnLabel,
    sampleTemplateLockOffLabel: labels.sampleTemplateLockOffLabel,
  };
}
