import { useMemo } from "react";
import { resolveTranslation } from "../i18n";

interface UseAppLabelsArgs {
  t: ReturnType<typeof resolveTranslation>;
  workflowMode: "generation" | "manual";
}

export function useAppLabels({ t, workflowMode }: UseAppLabelsArgs) {
  return useMemo(() => {
    const workflowGenerationLabel = t.workflowModeGeneration ?? "Pallet generation";
    const workflowManualLabel = t.workflowModeManual ?? "Manual layout";

    return {
      windowResolutionLabel: t.windowResolution ?? "Window resolution",
      diagnosticsRuntimeTelemetryLabel: t.diagnosticsRuntimeTelemetryLabel ?? "Runtime telemetry",
      diagnosticsLayoutChecksLabel: t.diagnosticsLayoutChecksLabel ?? "Layout checks",
      fpsLabel: t.fpsLabel ?? "FPS",
      cpuSystemUtilizationLabel: t.cpuSystemUtilizationLabel ?? "CPU utilization (system)",
      cpuAppUtilizationLabel: t.cpuAppUtilizationLabel ?? "CPU utilization (app)",
      memorySystemUsedLabel: t.memorySystemUsedLabel ?? "Memory used (system)",
      memorySystemTotalLabel: t.memorySystemTotalLabel ?? "Memory total (system)",
      workingSetAppLabel: t.workingSetAppLabel ?? "Working set (app)",
      privateMemoryAppLabel: t.privateMemoryAppLabel ?? "Private memory (app)",
      workflowLabel: t.workflowLabel ?? "Workflow",
      workflowGenerationLabel,
      workflowManualLabel,
      generateCartonsLabel: t.generateCartons ?? "Generate cartons",
      calculateFullLayoutLabel: t.calculateFullLayout ?? "Calculate full layout",
      calculateMissingCartonsLabel: t.calculateMissingCartons ?? "Calculate missing cartons",
      generateMoreCartonsLabel: t.generateMoreCartons ?? "Generate missing cartons",
      regenerateAllCartonsLabel: t.regenerateAllCartons ?? "Generate all cartons again",
      switchToManualEditingLabel: t.switchToManualEditing ?? "Switch to manual editing",
      switchToPalletGenerationLabel: t.switchToPalletGeneration ?? "Switch to pallet generation",
      palletPanelLabel: t.palletPanelLabel ?? "Pallet panel",
      refreshAppLabel: t.refreshAppLabel ?? "Refresh app",
      languageLabel: t.languageLabel ?? "Language",
      settingsLabel: t.settingsLabel ?? "Settings",
      settingsSaveLabel: t.settingsSaveLabel ?? "Save settings",
      settingsRestoreDefaultsLabel: t.settingsRestoreDefaultsLabel ?? "Restore to default",
      uiZoomAndScaleLabel: t.uiZoomAndScaleLabel ?? "UI Zoom and Scale",
      uiAccessOpenLabel: t.uiAccessOpenLabel ?? "Open",
      uiAccessCloseLabel: t.uiAccessCloseLabel ?? "Close",
      uiScaleLabel: t.uiScaleLabel ?? "UI scale",
      uiZoomLabel: t.uiZoomLabel ?? "UI zoom",
      shortcutActivationLabel: t.shortcutActivationLabel ?? "Activation shortcut",
      shortcutPressLabel: t.shortcutPressLabel ?? "Press shortcut...",
      closeLabel: t.closeLabel ?? "Close",
      closeUiZoomAndScaleLabel: t.closeUiZoomAndScaleLabel ?? "Close UI zoom and scale",
      closeDiagnosticsLabel: t.closeDiagnosticsLabel ?? "Close diagnostics",
      currentWorkflowLabel: workflowMode === "manual" ? workflowManualLabel : workflowGenerationLabel,
      diagnosticsHint: workflowMode === "manual"
        ? (t.diagnosticsHintManual ?? "No diagnostics data yet. Run Generate cartons first.")
        : (t.diagnosticsHintGeneration ?? "No diagnostics data yet. Run Calculate full layout first."),
      updateCheckTitle: t.updateCheckTitle ?? "Check for updates",
      updateCheckQuestion: t.updateCheckQuestion ?? "Do you want to check if a newer version was released?",
      updateCheckYesLabel: t.updateCheckYesLabel ?? "Yes",
      updateCheckNoLabel: t.updateCheckNoLabel ?? "No",
      workflowProgressTitleCalculate: t.workflowProgressTitleCalculate ?? "Calculating layout",
      workflowProgressTitleCalculateMissing: t.workflowProgressTitleCalculateMissing ?? "Calculating missing cartons",
      cancelLabel: t.cancel ?? "Cancel",
      workflowProgressStatusLabel: t.workflowProgressStatusLabel ?? "Status",
      workflowProgressElapsedLabel: t.workflowProgressElapsedLabel ?? "Elapsed",
      workflowProgressTrialLabel: t.workflowProgressTrialLabel ?? "Trial",
      workflowProgressPalletLabel: t.workflowProgressPalletLabel ?? "Pallet",
      workflowProgressLayerLabel: t.workflowProgressLayerLabel ?? "Layer",
      workflowProgressPreparingLabel: t.workflowProgressPreparingLabel ?? "Preparing workflow",
      workflowProgressAnalyzingManualSeedLabel: t.workflowProgressAnalyzingManualSeedLabel ?? "Analyzing preserved layout",
      workflowProgressTryingTemplateLockLabel: t.workflowProgressTryingTemplateLockLabel ?? "Trying template lock",
      workflowProgressTemplateContinuationLabel: t.workflowProgressTemplateContinuationLabel ?? "Continuing template pattern",
      workflowProgressPackingLayoutLabel: t.workflowProgressPackingLayoutLabel ?? "Packing layout",
      workflowProgressComparingFallbackLabel: t.workflowProgressComparingFallbackLabel ?? "Comparing fallback layout",
      workflowProgressPackingSupplementaryLabel: t.workflowProgressPackingSupplementaryLabel ?? "Packing remainder",
      packedUnitsLabel: t.packedUnits ?? "Packed units",
      palletCountLabel: t.palletCount ?? "Pallets",
      layersLabel: t.layers ?? "Layers",
      layoutSamplesLabel: t.layoutSamplesLabel ?? "Layout samples",
      saveLayoutSampleLabel: t.saveLayoutSampleLabel ?? "Save layout sample",
      loadLayoutSampleLabel: t.loadLayoutSampleLabel ?? "Load layout sample",
      sampleFolderLabel: t.sampleFolderLabel ?? "Sample folder",
      sampleChooseFolderLabel: t.sampleChooseFolderLabel ?? "Choose folder",
      sampleChangeFolderLabel: t.sampleChangeFolderLabel ?? "Change folder",
      sampleFolderNotSelectedLabel: t.sampleFolderNotSelectedLabel ?? "No folder selected",
      sampleNameLabel: t.sampleNameLabel ?? "Sample name",
      sampleNamePlaceholder: t.sampleNamePlaceholder ?? "e.g. centered_mix_001",
      sampleStrategyLabel: t.sampleStrategyLabel ?? "Layout strategy",
      sampleStrategyBothLabel: t.sampleStrategyBoth ?? "Compatible with both strategies",
      sampleSaveActionLabel: t.sampleSaveActionLabel ?? "Save sample",
      sampleSavingLabel: t.sampleSavingLabel ?? "Saving...",
      sampleSavedPrefix: t.sampleSavedPrefix ?? "Saved sample:",
      sampleSaveFailedPrefix: t.sampleSaveFailedPrefix ?? "Save failed:",
      sampleLoadFileLabel: t.sampleLoadFileLabel ?? "Sample file",
      sampleLoadNoSamplesLabel: t.sampleLoadNoSamplesLabel ?? "No valid JSON samples found",
      sampleReloadFolderLabel: t.sampleReloadFolderLabel ?? "Reload sample folder",
      sampleLoadActionLabel: t.sampleLoadActionLabel ?? "Load sample",
      sampleLoadingLabel: t.sampleLoadingLabel ?? "Loading...",
      sampleLoadedPrefix: t.sampleLoadedPrefix ?? "Loaded sample:",
      sampleLoadFailedPrefix: t.sampleLoadFailedPrefix ?? "Load failed:",
      sampleLoadNoFileSelectedLabel: t.sampleLoadNoFileSelectedLabel ?? "No sample selected",
      sampleDatabaseLabel: t.sampleDatabaseLabel ?? "Sample database",
      sampleDatabaseFolderLabel: t.sampleDatabaseFolderLabel ?? "Sample database folder",
      sampleDatabaseChooseFolderLabel: t.sampleDatabaseChooseFolderLabel ?? "Choose folder",
      sampleDatabaseReloadLabel: t.sampleDatabaseReloadLabel ?? "Reload",
      sampleDatabaseScanningLabel: t.sampleDatabaseScanningLabel ?? "Scanning sample database...",
      sampleDatabaseSummaryPrefix: t.sampleDatabaseSummaryPrefix ?? "JSON samples",
      sampleGuidanceActiveLabel: t.sampleGuidanceActiveLabel ?? "Sample guidance",
      sampleGuidanceCenterLabel: t.sampleGuidanceCenterLabel ?? "compact center",
      sampleGuidanceEdgeLabel: t.sampleGuidanceEdgeLabel ?? "aligned edges",
      sampleGuidanceOffManualLabel: t.sampleGuidanceOffManualLabel ?? "off (manual switch)",
      sampleGuidanceOffNoDirectionalLabel: t.sampleGuidanceOffNoDirectionalLabel ?? "off (no eligible generation samples yet)",
      sampleGuidanceSwitchLabel: t.sampleGuidanceSwitchLabel ?? "Guidance switch",
      sampleGuidanceOnLabel: t.sampleGuidanceOnLabel ?? "On",
      sampleGuidanceOffOptionLabel: t.sampleGuidanceOffOptionLabel ?? "Off",
      sampleGuidanceStrengthLabel: t.sampleGuidanceStrengthLabel ?? "Guidance strength",
      sampleGuidanceCfgScaleLabel: t.sampleGuidanceCfgScaleLabel ?? "Guidance CFG scale",
      sampleGuidanceStepsLabel: t.sampleGuidanceStepsLabel ?? "Guidance steps",
      sampleGuidanceSeedLabel: t.sampleGuidanceSeedLabel ?? "Guidance seed",
      sampleGuidanceFilterLabel: t.sampleGuidanceFilterLabel ?? "Sample filter",
      sampleGuidanceFilterAllLabel: t.sampleGuidanceFilterAllLabel ?? "All",
      sampleGuidanceFilterDimsLabel: t.sampleGuidanceFilterDimsLabel ?? "Dims only",
      sampleGuidanceFilterShapeLabel: t.sampleGuidanceFilterShapeLabel ?? "Shape match",
      sampleGuidanceFilterExactLabel: t.sampleGuidanceFilterExactLabel ?? "Exact match",
      sampleTemplateLockLabel: t.sampleTemplateLockLabel ?? "Template lock",
      sampleTemplateLockOnLabel: t.sampleTemplateLockOnLabel ?? "On",
      sampleTemplateLockOffLabel: t.sampleTemplateLockOffLabel ?? "Off",
      templateLockReadyLabel: t.sampleTemplateLockReadyLabel ?? "Template lock: ready",
      templateLockNoMatchLabel: t.sampleTemplateLockNoMatchLabel ?? "Template lock: no compatible sample",
      templateLockShapeMatchLabel: t.sampleTemplateLockShapeMatchLabel ?? "shape-match",
      templateLockExactMatchLabel: t.sampleTemplateLockExactMatchLabel ?? "exact-match",
    };
  }, [t, workflowMode]);
}

export type AppLabels = ReturnType<typeof useAppLabels>;
