import { useMemo } from "react";
import type { SidebarProps } from "../components/Sidebar";
import type { UseSidebarPropsArgs } from "./sidebarPropsTypes";
import { useSidebarBindings } from "./useSidebarBindings";

export function useSidebarProps({
  pallet,
  setPallet,
  cartons,
  setCartons,
  language,
  setLanguage,
  t,
  labels,
  workflowMode,
  result,
  generationSeedResult,
  manualCartons,
  handleCalculate,
  handleCalculateMissing,
  handleGenerateManualAgain,
  handleGenerateManualMore,
  workflowBusyKind,
  switchWorkflowMode,
  sampleDatabasePanelVisible,
  sampleDatabaseFolderPath,
  sampleDatabaseData,
  sampleDatabaseLoading,
  sampleDatabaseError,
  handleChooseSampleDatabaseFolder,
  handleReloadSampleDatabase,
  sampleDatabaseStatusSummaryText,
  sampleGuidanceEnabled,
  setSampleGuidanceEnabled,
  sampleGuidanceStrengthPercent,
  setSampleGuidanceStrengthPercent,
  sampleGuidanceCfgScalePercent,
  handleSampleGuidanceCfgScalePercentChange,
  sampleGuidanceSteps,
  handleSampleGuidanceStepsChange,
  sampleGuidanceSeed,
  handleSampleGuidanceSeedChange,
  sampleGuidanceFilter,
  setSampleGuidanceFilter,
  sampleTemplateLockEnabled,
  setSampleTemplateLockEnabled,
}: UseSidebarPropsArgs): SidebarProps {
  const { actionBindings, sampleDatabaseBindings } = useSidebarBindings({
    workflowMode,
    manualCartons,
    result,
    generationSeedResult,
    labels,
    handleCalculate,
    handleCalculateMissing,
    handleGenerateManualAgain,
    handleGenerateManualMore,
    workflowBusyKind,
    switchWorkflowMode,
    sampleDatabasePanelVisible,
    sampleDatabaseFolderPath,
    sampleDatabaseData,
    sampleDatabaseLoading,
    sampleDatabaseError,
    handleChooseSampleDatabaseFolder,
    handleReloadSampleDatabase,
    sampleDatabaseStatusSummaryText,
    sampleGuidanceEnabled,
    setSampleGuidanceEnabled,
    sampleGuidanceStrengthPercent,
    setSampleGuidanceStrengthPercent,
    sampleGuidanceCfgScalePercent,
    handleSampleGuidanceCfgScalePercentChange,
    sampleGuidanceSteps,
    handleSampleGuidanceStepsChange,
    sampleGuidanceSeed,
    handleSampleGuidanceSeedChange,
    sampleGuidanceFilter,
    setSampleGuidanceFilter,
    sampleTemplateLockEnabled,
    setSampleTemplateLockEnabled,
  });

  return useMemo(() => {
    return {
      workflowMode,
      pallet,
      setPallet,
      cartons,
      setCartons,
      ...actionBindings,
      language,
      setLanguage,
      t,
      showHeader: false,
      showLanguageSection: false,
      ...sampleDatabaseBindings,
      showExtraPalletMode: workflowMode === "generation",
      className: "layout-sidebar",
    };
  }, [
    actionBindings,
    cartons,
    language,
    pallet,
    sampleDatabaseBindings,
    setCartons,
    setLanguage,
    setPallet,
    t,
    workflowMode,
  ]);
}
