import type { ViewerStageProps } from "../components/ViewerStage";
import type { UseViewerStagePropsArgs } from "./viewerStagePropsTypes";
import { buildDiagnosticsSummary } from "../lib/diagnostics";

export function mapViewerStageProps({
  pallet,
  result,
  visibleLayers,
  setVisibleLayers,
  t,
  workflowMode,
  manualCartons,
  onManualCartonUpdate,
  uiOverlays,
  uiScale,
  uiZoom,
  uiScaleMin,
  uiScaleMax,
  uiZoomMin,
  uiZoomMax,
  onSetUiScale,
  onSetUiZoom,
  updateCheckModalOpen,
  onConfirmUpdateCheck,
  onCloseUpdateCheck,
  labels,
}: UseViewerStagePropsArgs): ViewerStageProps {
  const maxLayerCount = result
    ? result.pallets.reduce((max, placed) => Math.max(max, placed.result.layers.length), 0)
    : 0;
  const diagnosticsSummary = buildDiagnosticsSummary(result, pallet);

  return {
    pallet,
    result,
    visibleLayers,
    setVisibleLayers,
    t,
    workflowMode,
    manualCartons,
    onManualCartonUpdate,
    maxLayerCount,
    uiAccessOpen: uiOverlays.uiAccessOpen,
    uiAccessModalRef: uiOverlays.uiAccessModalRef,
    uiAccessModalStyle: uiOverlays.uiAccessModalStyle,
    uiZoomAndScaleLabel: labels.uiZoomAndScaleLabel,
    closeLabel: labels.closeLabel,
    closeUiZoomAndScaleLabel: labels.closeUiZoomAndScaleLabel,
    uiScaleLabel: labels.uiScaleLabel,
    uiZoomLabel: labels.uiZoomLabel,
    uiScale,
    uiZoom,
    uiScaleMin,
    uiScaleMax,
    uiZoomMin,
    uiZoomMax,
    onSetUiScale,
    onSetUiZoom,
    onCloseUiAccess: uiOverlays.closeUiAccess,
    diagnosticsOpen: uiOverlays.diagnosticsOpen,
    diagnosticsModalRef: uiOverlays.diagnosticsModalRef,
    diagnosticsModalStyle: uiOverlays.diagnosticsModalStyle,
    closeDiagnosticsLabel: labels.closeDiagnosticsLabel,
    diagnostics: diagnosticsSummary,
    requestedUnitsLabel: t.requestedUnits,
    packedUnitsLabel: t.packedUnits,
    overlapCountLabel: t.overlapCount,
    boundsViolationsLabel: t.boundsViolations,
    windowResolutionLabel: labels.windowResolutionLabel,
    hardChecksLabel: t.hardChecks,
    checksIssuesLabel: t.checksIssues,
    checksOkLabel: t.checksOk,
    diagnosticsHint: labels.diagnosticsHint,
    windowWidth: uiOverlays.windowSize.width,
    windowHeight: uiOverlays.windowSize.height,
    onCloseDiagnostics: uiOverlays.closeDiagnostics,
    onBeginDragUiAccess: (event) => uiOverlays.beginDrag("uiAccess", event),
    onBeginDragDiagnostics: (event) => uiOverlays.beginDrag("diagnostics", event),
    onDragPointerMoveUiAccess: (event) => uiOverlays.handleDragPointerMove("uiAccess", event),
    onDragPointerMoveDiagnostics: (event) => uiOverlays.handleDragPointerMove("diagnostics", event),
    onEndDragPointer: uiOverlays.endDragPointer,
    updateCheckModalOpen,
    updateCheckTitle: labels.updateCheckTitle,
    updateCheckQuestion: labels.updateCheckQuestion,
    updateCheckYesLabel: labels.updateCheckYesLabel,
    updateCheckNoLabel: labels.updateCheckNoLabel,
    onConfirmUpdateCheck,
    onCloseUpdateCheck,
  };
}
