import type { SidebarSectionsProps } from "./sidebarSectionsTypes";
import type { BuildSidebarSectionsPropsArgs } from "./sidebarPropsMappingTypes";

export function buildSidebarSectionsProps({
  props,
  sidebarState,
  resolvedLabels,
  showLanguageSection,
  showSampleDatabaseSection,
  showExtraPalletMode,
}: BuildSidebarSectionsPropsArgs): SidebarSectionsProps {
  return {
    showLanguageSection,
    showSampleDatabaseSection,
    collapsedSections: sidebarState.collapsedSections,
    toggleSection: sidebarState.toggleSection,
    language: props.language,
    setLanguage: props.setLanguage,
    t: props.t,
    resolvedLabels,
    sampleDatabaseFolderPath: props.sampleDatabaseFolderPath ?? "",
    sampleDatabaseSummary: props.sampleDatabaseSummary ?? null,
    sampleDatabaseLoading: props.sampleDatabaseLoading ?? false,
    sampleDatabaseError: props.sampleDatabaseError ?? null,
    onChooseSampleDatabaseFolder: props.onChooseSampleDatabaseFolder,
    onReloadSampleDatabase: props.onReloadSampleDatabase,
    sampleDatabaseGuidanceSummary: props.sampleDatabaseGuidanceSummary,
    sampleGuidanceEnabled: props.sampleGuidanceEnabled,
    onSampleGuidanceEnabledChange: props.onSampleGuidanceEnabledChange,
    sampleGuidanceStrengthPercent: props.sampleGuidanceStrengthPercent,
    onSampleGuidanceStrengthPercentChange: props.onSampleGuidanceStrengthPercentChange,
    sampleGuidanceCfgScalePercent: props.sampleGuidanceCfgScalePercent,
    onSampleGuidanceCfgScalePercentChange: props.onSampleGuidanceCfgScalePercentChange,
    sampleGuidanceSteps: props.sampleGuidanceSteps,
    onSampleGuidanceStepsChange: props.onSampleGuidanceStepsChange,
    sampleGuidanceSeed: props.sampleGuidanceSeed,
    onSampleGuidanceSeedChange: props.onSampleGuidanceSeedChange,
    sampleGuidanceFilter: props.sampleGuidanceFilter,
    onSampleGuidanceFilterChange: props.onSampleGuidanceFilterChange,
    sampleTemplateLockEnabled: props.sampleTemplateLockEnabled,
    onSampleTemplateLockEnabledChange: props.onSampleTemplateLockEnabledChange,
    pallet: props.pallet,
    setPallet: props.setPallet,
    showExtraPalletMode,
    editing: sidebarState.editing,
    setEditing: sidebarState.setEditing,
    handleAdd: sidebarState.handleAdd,
    handleEdit: sidebarState.handleEdit,
    cartons: props.cartons,
    totalCartons: sidebarState.totalCartons,
    hasManyCartonRows: sidebarState.hasManyCartonRows,
    handleStartEdit: sidebarState.handleStartEdit,
    handleRemoveCarton: sidebarState.handleRemoveCarton,
  };
}
