import type { CartonInput, PalletInput, SampleGuidanceFilter } from "../../lib/packer";
import type { Language, Translations } from "../../i18n";
import type { WorkflowMode } from "../Visualizer";

export interface SidebarProps {
  workflowMode: WorkflowMode;
  pallet: PalletInput;
  setPallet: (p: PalletInput) => void;
  cartons: CartonInput[];
  setCartons: (c: CartonInput[]) => void;
  onPrimaryAction: () => void;
  primaryActionLabel: string;
  onSecondaryAction?: () => void;
  secondaryActionLabel?: string;
  onWorkflowModeAction?: () => void;
  workflowModeActionLabel?: string;
  dualActionPrimaryAccent?: boolean;
  actionsDisabled?: boolean;
  language: Language;
  setLanguage: (language: Language) => void;
  t: Translations;
  className?: string;
  showHeader?: boolean;
  showLanguageSection?: boolean;
  showSampleDatabaseSection?: boolean;
  sampleDatabaseFolderPath?: string;
  sampleDatabaseSummary?: {
    totalFiles: number;
    validFiles: number;
    invalidFiles: number;
    firstDescriptors: string[];
  } | null;
  sampleDatabaseLoading?: boolean;
  sampleDatabaseError?: string | null;
  onChooseSampleDatabaseFolder?: () => void;
  onReloadSampleDatabase?: () => void;
  sampleDatabaseLabel?: string;
  sampleDatabaseFolderLabel?: string;
  sampleDatabaseChooseFolderLabel?: string;
  sampleDatabaseReloadLabel?: string;
  sampleDatabaseScanningLabel?: string;
  sampleDatabaseSummaryPrefix?: string;
  sampleDatabaseFolderNotSelectedLabel?: string;
  sampleDatabaseGuidanceSummary?: string;
  sampleGuidanceEnabled?: boolean;
  onSampleGuidanceEnabledChange?: (enabled: boolean) => void;
  sampleGuidanceModeLabel?: string;
  sampleGuidanceModeOnLabel?: string;
  sampleGuidanceModeOffLabel?: string;
  sampleGuidanceStrengthPercent?: number;
  onSampleGuidanceStrengthPercentChange?: (value: number) => void;
  sampleGuidanceStrengthLabel?: string;
  sampleGuidanceCfgScalePercent?: number;
  onSampleGuidanceCfgScalePercentChange?: (value: number) => void;
  sampleGuidanceCfgScaleLabel?: string;
  sampleGuidanceSteps?: number;
  onSampleGuidanceStepsChange?: (value: number) => void;
  sampleGuidanceStepsLabel?: string;
  sampleGuidanceSeed?: number;
  onSampleGuidanceSeedChange?: (value: number) => void;
  sampleGuidanceSeedLabel?: string;
  sampleGuidanceFilter?: SampleGuidanceFilter;
  onSampleGuidanceFilterChange?: (value: SampleGuidanceFilter) => void;
  sampleGuidanceFilterLabel?: string;
  sampleGuidanceFilterAllLabel?: string;
  sampleGuidanceFilterDimsLabel?: string;
  sampleGuidanceFilterShapeLabel?: string;
  sampleGuidanceFilterExactLabel?: string;
  sampleTemplateLockEnabled?: boolean;
  onSampleTemplateLockEnabledChange?: (enabled: boolean) => void;
  sampleTemplateLockLabel?: string;
  sampleTemplateLockOnLabel?: string;
  sampleTemplateLockOffLabel?: string;
  showExtraPalletMode?: boolean;
}
